{% set name = "cryotypes" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cryotypes-{{ version }}.tar.gz
  sha256: f793daa00d1ace96ac60dc38072b189aba1d737351b89de2ba5475c26f74a213

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - einops
    - python >=3.7
    - numpy
    - pandas
    - scipy
    - typing-extensions

test:
  imports:
    - cryotypes
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cryotypes
  summary: Generalized python types and validators for cryoEM data.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/teamtomo/cryotypes

extra:
  recipe-maintainers:
    - alisterburt
    - brisvag
    - goanpeca
